name: euics
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - asttokens=2.4.1
  - attrs=23.1.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cuda-cccl=12.3.101
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.3.101
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.1.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - giflib=5.2.1
  - gmpy2=2.1.2
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.101
  - libcurand-dev=10.3.4.101
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - nest-asyncio=1.5.8
  - networkx=3.1
  - numexpr=2.8.7
  - numpy-base=1.26.2
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.1.0
  - ply=3.11
  - prompt-toolkit=3.0.41
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyg=2.5.0
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.12
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xmltodict=0.13.0
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - beautifulsoup4==4.12.3
      - bottleneck==1.3.8
      - currencyconverter==0.17.20
      - cython==3.0.8
      - decorator==4.4.2
      - greenlet==3.0.3
      - numpy==1.26.4
      - pandas==2.2.2
      - psycopg2==2.9.9
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - seaborn==0.13.2
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchaudio==2.1.1
      - torchinfo==1.8.0
      - torchvision==0.16.1
      - torchviz==0.0.2
      - tzdata==2024.1
